name=input("enter name: ")
mark=int(input("enter markes: "))
number=int(input("enter Ph number: "))
a="the name of the student is {}, his markes are {} and phone number {}".format(name,mark,number)
print(a)